### ISSUE TITLE
Push fails if tag exists

### ISSUE THREAD

**Issue by eddiemonge** [stevemao/conventional-github-releaser#5]
This seems to fail because it tries to do a post instead of a patch if a tag already exists.

**Comment by stevemao** [comment]
If the tag doesn't exist it cannot make a GitHub release on that tag. How can I replicate this?
https://github.com/stevemao/grunt-conventional-github-releaser/blob/master/Gruntfile.js#L156-L157
It must bump first then release. Also see https://gist.github.com/stevemao/280ef22ee861323993a0#file-np-sh-L26-L27

**Comment by eddiemonge** [comment]
Sorry, didn't mean tag. Meant release.

**Comment by stevemao** [comment]
Yeah, this is by design. I don't want to overwrite a release if already exists. People might have their releases before using this module. They have to remove them if they want to overwrite the releases.

**Comment by eddiemonge** [comment]
maybe there could be an option like `force` so they don't have to take the extra step of deleting it. This is exactly what patch is for, to modify if.

**Comment by stevemao** [comment]
I thought about this. But it's hard so I created [github-remove-all-releases](https://github.com/stevemao/github-remove-all-releases). I believe making this module minimum is easier for me.
