### ISSUE TITLE
Fails silently if package.json does not have a repository

### ISSUE THREAD

**Issue by brianpeiris** [stevemao/conventional-github-releaser#6]

**Comment by stevemao** [comment]
Do you specify your repo manually?

**Comment by psyrendust** [comment]
@brianpeiris Could you post a copy of your package.json?

**Comment by brianpeiris** [comment]
@stevemao Nope, never tried specifying it manually. I just ended up adding the field and it's fine now. @psyrendust: https://github.com/AltspaceVR/AltspaceSDK/blob/db424b082afcd60ab030886f370e064cb5b1decd/package.json
